### ISSUE TITLE
Unable to update Backdrop core with GUI.

### ISSUE THREAD

**Issue by izmeez** [devpanel-demo/backdrop-cms-quickstart#33]
The Backdrop Status report and available updates report show that a new release is available. However, it is not possible to update to the new release using the GUI. 

When attempting to do the update the first step goes to the url `admin/config/system/updates` and the screen indicates that FTP is required:
![df-backdrop-core-update-requires-FTP-access-screenshot](https://github.com/user-attachments/assets/d1d85106-c459-480a-af69-e0050d3a32e1)

However, the next step, downloading the new release proceeds successfully:
![df-backdrop-core-update-downloaded-screenshot](https://github.com/user-attachments/assets/d4419743-85fe-4006-8ecf-6e7bc73d87f0)

Then the subsequent step goes to the url `core/authorize.php` where the following is displayed:
![df-bd-core-update-manager-needs-FTP-screenshot](https://github.com/user-attachments/assets/3a394ac1-430f-463b-96f8-ae96125ddf67)

This issue was previously identified (https://helpdesk.devpanel.com/issues/11) and it was hoped that changes to permissions would fix this. Changing the permissions as described in https://helpdesk.devpanel.com/issues/11#note-2 does not work now.

The issue appears to be related to the `core/authorize.php` file.

**Comment by sklakhani** [comment]
@izmeez would you recommend that we change the default to Looser permissions? @devpanel-kha I think if you can do that, then it might solve a lot of issues, not just with backdrop but with other apps as well.

**Comment by sklakhani** [comment]
it's just that... with looser permissions, the web server can modify code... with strict permissions, you have to use the command line to modify code. In your case, it looks like the web ui just calls some app that updates the code, so it's throwing an error, but does the job regardless, right?

**Comment by thanhkha159684** [comment]
Hi @izmeez @sklakhani there is a bug for file permision
I just fixed and confirm that you can update backdrop core, install new module on the UI.
For Drupal 7. It is not allow to update core in the UI but you can install new module via UI
![Screenshot from 2024-09-19 11-06-44](https://github.com/user-attachments/assets/e1ca25c4-12ce-4ecf-8fbd-4f61a24e9792)

So I close this issue. Feel free to re-open if you have any feedback!

**Comment by devpanel-kha** [comment]
Hi @izmeez @sklakhani there is a bug for file permision
I just fixed and confirm that you can update backdrop core, install new module on the UI.

For Drupal 7. It is not allow to update core in the UI but you can install new module via UI
![Screenshot from 2024-09-19 11-06-44](https://github.com/user-attachments/assets/5a320566-5df2-48f4-88d3-c42543dd137d)


So I close this issue. Feel free to re-open if you have any feedback!
